from enum import Enum


class ModelAnalyzerToolName(str, Enum):
    SHAP_INSIGHT_NARRATIVE = "SHAP_INSIGHT_NARRATIVE"
    SHAP_SUMMARY_PLOT = "SHAP_SUMMARY_PLOT"
    SHAP_FEATURE_IMPORTANCE = "SHAP_FEATURE_IMPORTANCE"
    CONFUSION_MATRIX_PLOT = "CONFUSION_MATRIX_PLOT"
    F1_SCORE = "F1_SCORE"